// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: active_players.sql

package db

import (
	"context"
	"database/sql"
)

const claimPlayer = `-- name: ClaimPlayer :exec
UPDATE players SET active = 1 WHERE id = ? AND active = 0
`

func (q *Queries) ClaimPlayer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, claimPlayer, id)
	return err
}

const getAvailablePlayerById = `-- name: GetAvailablePlayerById :one
SELECT id, name, handicap, active, course_tees_id, tournament_id, team_id, refreshtokenversion, created_at FROM players WHERE id = ? AND active = 1 LIMIT 1
`

func (q *Queries) GetAvailablePlayerById(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getAvailablePlayerById, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handicap,
		&i.Active,
		&i.CourseTeesID,
		&i.TournamentID,
		&i.TeamID,
		&i.Refreshtokenversion,
		&i.CreatedAt,
	)
	return i, err
}

const getAvailablePlayers = `-- name: GetAvailablePlayers :many
SELECT 
    p.id,
    p.name,
    p.handicap,
    p.active,
    p.course_tees_id,
    p.tournament_id,
    p.team_id,
    p.refreshtokenversion,
    p.created_at,
    ct.rating as tee_rating,
    ct.slope as tee_slope
FROM players p
LEFT JOIN course_tees ct ON p.course_tees_id = ct.id
WHERE
    p.tournament_id = ?1
    AND p.active = 0
ORDER BY p.name
`

type GetAvailablePlayersRow struct {
	ID                  int64
	Name                string
	Handicap            sql.NullFloat64
	Active              bool
	CourseTeesID        int64
	TournamentID        int64
	TeamID              int64
	Refreshtokenversion int64
	CreatedAt           sql.NullTime
	TeeRating           sql.NullFloat64
	TeeSlope            sql.NullInt64
}

func (q *Queries) GetAvailablePlayers(ctx context.Context, tournamentID int64) ([]GetAvailablePlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAvailablePlayers, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailablePlayersRow
	for rows.Next() {
		var i GetAvailablePlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handicap,
			&i.Active,
			&i.CourseTeesID,
			&i.TournamentID,
			&i.TeamID,
			&i.Refreshtokenversion,
			&i.CreatedAt,
			&i.TeeRating,
			&i.TeeSlope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unclaimPlayer = `-- name: UnclaimPlayer :exec
UPDATE players SET active = 0 WHERE id = ? AND active = 1
`

func (q *Queries) UnclaimPlayer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unclaimPlayer, id)
	return err
}
