// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: active_players.sql

package db

import (
	"context"
	"database/sql"
)

const getAvailablePlayerById = `-- name: GetAvailablePlayerById :one
SELECT p.id as player_id, p.name, p.handicap, t.id as team_id, t.tournament_id as tournament_id
FROM players p
JOIN team_players tp ON tp.player_id = p.id
JOIN teams t ON t.id = tp.team_id
WHERE t.tournament_id = ? AND player_id = ?
`

type GetAvailablePlayerByIdParams struct {
	TournamentID sql.NullInt64
	PlayerID     sql.NullInt64
}

type GetAvailablePlayerByIdRow struct {
	PlayerID     int64
	Name         string
	Handicap     sql.NullFloat64
	TeamID       int64
	TournamentID sql.NullInt64
}

func (q *Queries) GetAvailablePlayerById(ctx context.Context, arg GetAvailablePlayerByIdParams) (GetAvailablePlayerByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAvailablePlayerById, arg.TournamentID, arg.PlayerID)
	var i GetAvailablePlayerByIdRow
	err := row.Scan(
		&i.PlayerID,
		&i.Name,
		&i.Handicap,
		&i.TeamID,
		&i.TournamentID,
	)
	return i, err
}

const getAvailablePlayers = `-- name: GetAvailablePlayers :many
SELECT p.id as player_id, p.name, p.handicap, t.id as team_id, t.tournament_id as tournament_id
FROM players p
JOIN team_players tp ON tp.player_id = p.id
JOIN teams t ON t.id = tp.team_id
WHERE t.tournament_id = ?
AND p.id NOT IN (
    SELECT atp.player_id FROM active_tournament_players atp WHERE atp.tournament_id = ?
)
ORDER BY p.name
`

type GetAvailablePlayersParams struct {
	TournamentID   sql.NullInt64
	TournamentID_2 int64
}

type GetAvailablePlayersRow struct {
	PlayerID     int64
	Name         string
	Handicap     sql.NullFloat64
	TeamID       int64
	TournamentID sql.NullInt64
}

func (q *Queries) GetAvailablePlayers(ctx context.Context, arg GetAvailablePlayersParams) ([]GetAvailablePlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAvailablePlayers, arg.TournamentID, arg.TournamentID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailablePlayersRow
	for rows.Next() {
		var i GetAvailablePlayersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Name,
			&i.Handicap,
			&i.TeamID,
			&i.TournamentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeActivePlayer = `-- name: RemoveActivePlayer :exec
DELETE FROM active_tournament_players WHERE tournament_id = ? AND player_id = ?
`

type RemoveActivePlayerParams struct {
	TournamentID int64
	PlayerID     int64
}

func (q *Queries) RemoveActivePlayer(ctx context.Context, arg RemoveActivePlayerParams) error {
	_, err := q.db.ExecContext(ctx, removeActivePlayer, arg.TournamentID, arg.PlayerID)
	return err
}

const selectPlayer = `-- name: SelectPlayer :exec
INSERT INTO active_tournament_players (tournament_id, player_id) VALUES (?, ?)
`

type SelectPlayerParams struct {
	TournamentID int64
	PlayerID     int64
}

func (q *Queries) SelectPlayer(ctx context.Context, arg SelectPlayerParams) error {
	_, err := q.db.ExecContext(ctx, selectPlayer, arg.TournamentID, arg.PlayerID)
	return err
}
