// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: active_players.sql

package db

import (
	"context"
)

const claimPlayer = `-- name: ClaimPlayer :exec
UPDATE players SET active = 1 WHERE id = ? AND active = 0
`

func (q *Queries) ClaimPlayer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, claimPlayer, id)
	return err
}

const getAvailablePlayerById = `-- name: GetAvailablePlayerById :one
SELECT id, name, is_admin, handicap, active, course_tees_id, tournament_id, team_id, refreshtokenversion, created_at FROM players WHERE id = ? AND active = 1 LIMIT 1
`

func (q *Queries) GetAvailablePlayerById(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getAvailablePlayerById, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsAdmin,
		&i.Handicap,
		&i.Active,
		&i.CourseTeesID,
		&i.TournamentID,
		&i.TeamID,
		&i.Refreshtokenversion,
		&i.CreatedAt,
	)
	return i, err
}

const getAvailablePlayers = `-- name: GetAvailablePlayers :many
SELECT id, name, is_admin, handicap, active, course_tees_id, tournament_id, team_id, refreshtokenversion, created_at
FROM players
WHERE
    tournament_id = ?1
    AND active = 0
ORDER BY name
`

func (q *Queries) GetAvailablePlayers(ctx context.Context, tournamentID int64) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getAvailablePlayers, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsAdmin,
			&i.Handicap,
			&i.Active,
			&i.CourseTeesID,
			&i.TournamentID,
			&i.TeamID,
			&i.Refreshtokenversion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unclaimPlayer = `-- name: UnclaimPlayer :exec
UPDATE players SET active = 0 WHERE id = ? AND active = 1
`

func (q *Queries) UnclaimPlayer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unclaimPlayer, id)
	return err
}
