// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
)

const getAdminConfig = `-- name: GetAdminConfig :one
SELECT value FROM admin_config WHERE key = ? LIMIT 1
`

func (q *Queries) GetAdminConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAdminConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
