// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package db

import (
	"context"
	"database/sql"
)

const getAllCourses = `-- name: GetAllCourses :many
SELECT id, name FROM courses
`

type GetAllCoursesRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetAllCourses(ctx context.Context) ([]GetAllCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCoursesRow
	for rows.Next() {
		var i GetAllCoursesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseByTournamentID = `-- name: GetCourseByTournamentID :one
SELECT c.id, c.name, t.awarded_handicap
FROM courses c
JOIN tournaments t ON t.course_id = c.id
WHERE t.id = ?
`

type GetCourseByTournamentIDRow struct {
	ID              int64
	Name            string
	AwardedHandicap sql.NullFloat64
}

func (q *Queries) GetCourseByTournamentID(ctx context.Context, id int64) (GetCourseByTournamentIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseByTournamentID, id)
	var i GetCourseByTournamentIDRow
	err := row.Scan(&i.ID, &i.Name, &i.AwardedHandicap)
	return i, err
}

const getCourseHoles = `-- name: GetCourseHoles :many
SELECT id, hole_number, par, handicap, yardage 
FROM course_holes 
WHERE course_id = ?
ORDER BY hole_number ASC
`

type GetCourseHolesRow struct {
	ID         int64
	HoleNumber int64
	Par        int64
	Handicap   int64
	Yardage    int64
}

func (q *Queries) GetCourseHoles(ctx context.Context, courseID int64) ([]GetCourseHolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCourseHoles, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseHolesRow
	for rows.Next() {
		var i GetCourseHolesRow
		if err := rows.Scan(
			&i.ID,
			&i.HoleNumber,
			&i.Par,
			&i.Handicap,
			&i.Yardage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
