// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: formats.sql

package db

import (
	"context"
	"database/sql"
)

const getAllFormats = `-- name: GetAllFormats :many
SELECT id, name, description, is_team_scoring FROM tournament_formats ORDER BY name
`

type GetAllFormatsRow struct {
	ID            int64
	Name          string
	Description   sql.NullString
	IsTeamScoring sql.NullBool
}

func (q *Queries) GetAllFormats(ctx context.Context) ([]GetAllFormatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFormats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFormatsRow
	for rows.Next() {
		var i GetAllFormatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsTeamScoring,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
