// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"
	"database/sql"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (token, tournament_id, expires_at, created_at, active)
VALUES (?, ?, ?, ?, 1)
RETURNING token, tournament_id, expires_at, created_at, active
`

type CreateInviteParams struct {
	Token        sql.NullString
	TournamentID int64
	ExpiresAt    sql.NullTime
	CreatedAt    sql.NullTime
}

type CreateInviteRow struct {
	Token        sql.NullString
	TournamentID int64
	ExpiresAt    sql.NullTime
	CreatedAt    sql.NullTime
	Active       sql.NullBool
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (CreateInviteRow, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.Token,
		arg.TournamentID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i CreateInviteRow
	err := row.Scan(
		&i.Token,
		&i.TournamentID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT token, tournament_id, expires_at, created_at, active FROM invites WHERE token = ?
`

type GetInviteRow struct {
	Token        sql.NullString
	TournamentID int64
	ExpiresAt    sql.NullTime
	CreatedAt    sql.NullTime
	Active       sql.NullBool
}

func (q *Queries) GetInvite(ctx context.Context, token sql.NullString) (GetInviteRow, error) {
	row := q.db.QueryRowContext(ctx, getInvite, token)
	var i GetInviteRow
	err := row.Scan(
		&i.Token,
		&i.TournamentID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}
