// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name, handicap, is_admin, created_at, tournament_id, team_id, course_tees_id) 
VALUES (?, ?, ?, ?, ?, ?, ?) 
RETURNING id, name, handicap, is_admin, created_at
`

type CreatePlayerParams struct {
	Name         string
	Handicap     sql.NullFloat64
	IsAdmin      sql.NullBool
	CreatedAt    sql.NullTime
	TournamentID int64
	TeamID       int64
	CourseTeesID int64
}

type CreatePlayerRow struct {
	ID        int64
	Name      string
	Handicap  sql.NullFloat64
	IsAdmin   sql.NullBool
	CreatedAt sql.NullTime
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.Name,
		arg.Handicap,
		arg.IsAdmin,
		arg.CreatedAt,
		arg.TournamentID,
		arg.TeamID,
		arg.CourseTeesID,
	)
	var i CreatePlayerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handicap,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getAllPlayers = `-- name: GetAllPlayers :many
SELECT id, name, handicap, is_admin, created_at FROM players ORDER BY name
`

type GetAllPlayersRow struct {
	ID        int64
	Name      string
	Handicap  sql.NullFloat64
	IsAdmin   sql.NullBool
	CreatedAt sql.NullTime
}

func (q *Queries) GetAllPlayers(ctx context.Context) ([]GetAllPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPlayersRow
	for rows.Next() {
		var i GetAllPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handicap,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, name, handicap, is_admin, created_at FROM players WHERE id = ?
`

type GetPlayerRow struct {
	ID        int64
	Name      string
	Handicap  sql.NullFloat64
	IsAdmin   sql.NullBool
	CreatedAt sql.NullTime
}

func (q *Queries) GetPlayer(ctx context.Context, id int64) (GetPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i GetPlayerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handicap,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}
