// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name, handicap, created_at, tournament_id, team_id, course_tees_id) 
VALUES (?, ?, ?, ?, ?, ?) 
RETURNING id, name, handicap, created_at
`

type CreatePlayerParams struct {
	Name         string
	Handicap     sql.NullFloat64
	CreatedAt    sql.NullTime
	TournamentID int64
	TeamID       int64
	CourseTeesID int64
}

type CreatePlayerRow struct {
	ID        int64
	Name      string
	Handicap  sql.NullFloat64
	CreatedAt sql.NullTime
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.Name,
		arg.Handicap,
		arg.CreatedAt,
		arg.TournamentID,
		arg.TeamID,
		arg.CourseTeesID,
	)
	var i CreatePlayerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handicap,
		&i.CreatedAt,
	)
	return i, err
}

const getAllPlayers = `-- name: GetAllPlayers :many
SELECT id, name, handicap, active, refreshTokenVersion, tournament_id, team_id, created_at FROM players ORDER BY name
`

type GetAllPlayersRow struct {
	ID                  int64
	Name                string
	Handicap            sql.NullFloat64
	Active              bool
	Refreshtokenversion int64
	TournamentID        int64
	TeamID              int64
	CreatedAt           sql.NullTime
}

func (q *Queries) GetAllPlayers(ctx context.Context) ([]GetAllPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPlayersRow
	for rows.Next() {
		var i GetAllPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handicap,
			&i.Active,
			&i.Refreshtokenversion,
			&i.TournamentID,
			&i.TeamID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, name, handicap, active, refreshTokenVersion, tournament_id, team_id, created_at FROM players WHERE id = ?
`

type GetPlayerRow struct {
	ID                  int64
	Name                string
	Handicap            sql.NullFloat64
	Active              bool
	Refreshtokenversion int64
	TournamentID        int64
	TeamID              int64
	CreatedAt           sql.NullTime
}

func (q *Queries) GetPlayer(ctx context.Context, id int64) (GetPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i GetPlayerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handicap,
		&i.Active,
		&i.Refreshtokenversion,
		&i.TournamentID,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayersByTournament = `-- name: GetPlayersByTournament :many
SELECT p.id, p.name, p.handicap, p.active, p.refreshTokenVersion, p.tournament_id, p.team_id, p.created_at, t.name as team_name
FROM players p
LEFT JOIN teams t ON p.team_id = t.id
WHERE p.tournament_id = ?
ORDER BY p.team_id, p.name
`

type GetPlayersByTournamentRow struct {
	ID                  int64
	Name                string
	Handicap            sql.NullFloat64
	Active              bool
	Refreshtokenversion int64
	TournamentID        int64
	TeamID              int64
	CreatedAt           sql.NullTime
	TeamName            sql.NullString
}

func (q *Queries) GetPlayersByTournament(ctx context.Context, tournamentID int64) ([]GetPlayersByTournamentRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayersByTournamentRow
	for rows.Next() {
		var i GetPlayersByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handicap,
			&i.Active,
			&i.Refreshtokenversion,
			&i.TournamentID,
			&i.TeamID,
			&i.CreatedAt,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :exec
UPDATE players 
SET name = ?, handicap = ?, active = ?, team_id = ?
WHERE id = ?
`

type UpdatePlayerParams struct {
	Name     string
	Handicap sql.NullFloat64
	Active   bool
	TeamID   int64
	ID       int64
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayer,
		arg.Name,
		arg.Handicap,
		arg.Active,
		arg.TeamID,
		arg.ID,
	)
	return err
}
