// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"
	"database/sql"
)

const addPlayerToTeam = `-- name: AddPlayerToTeam :exec
INSERT INTO team_players (team_id, player_id) VALUES (?, ?)
`

type AddPlayerToTeamParams struct {
	TeamID   sql.NullInt64
	PlayerID sql.NullInt64
}

func (q *Queries) AddPlayerToTeam(ctx context.Context, arg AddPlayerToTeamParams) error {
	_, err := q.db.ExecContext(ctx, addPlayerToTeam, arg.TeamID, arg.PlayerID)
	return err
}

const checkTeamExists = `-- name: CheckTeamExists :one
SELECT EXISTS(SELECT 1 FROM teams WHERE id = ? AND tournament_id = ?)
`

type CheckTeamExistsParams struct {
	ID           int64
	TournamentID sql.NullInt64
}

func (q *Queries) CheckTeamExists(ctx context.Context, arg CheckTeamExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkTeamExists, arg.ID, arg.TournamentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, tournament_id, started, finished, created_at) 
VALUES (?, ?, 0, 0, ?)
RETURNING id
`

type CreateTeamParams struct {
	Name         string
	TournamentID sql.NullInt64
	CreatedAt    sql.NullTime
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.Name, arg.TournamentID, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, tournament_id, started, finished FROM teams WHERE id = ?
`

type GetTeamRow struct {
	ID           int64
	Name         string
	TournamentID sql.NullInt64
	Started      sql.NullBool
	Finished     sql.NullBool
}

func (q *Queries) GetTeam(ctx context.Context, id int64) (GetTeamRow, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i GetTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TournamentID,
		&i.Started,
		&i.Finished,
	)
	return i, err
}

const getTeamPlayers = `-- name: GetTeamPlayers :many
SELECT p.id, p.name, p.handicap, p.is_admin, p.created_at, tp.tee
FROM players p
JOIN team_players tp ON tp.player_id = p.id
WHERE tp.team_id = ?
`

type GetTeamPlayersRow struct {
	ID        int64
	Name      string
	Handicap  sql.NullFloat64
	IsAdmin   sql.NullBool
	CreatedAt sql.NullTime
	Tee       sql.NullString
}

func (q *Queries) GetTeamPlayers(ctx context.Context, teamID sql.NullInt64) ([]GetTeamPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamPlayers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamPlayersRow
	for rows.Next() {
		var i GetTeamPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handicap,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.Tee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsByTournament = `-- name: GetTeamsByTournament :many
SELECT id, name, tournament_id, started, finished FROM teams WHERE tournament_id = ?
`

type GetTeamsByTournamentRow struct {
	ID           int64
	Name         string
	TournamentID sql.NullInt64
	Started      sql.NullBool
	Finished     sql.NullBool
}

func (q *Queries) GetTeamsByTournament(ctx context.Context, tournamentID sql.NullInt64) ([]GetTeamsByTournamentRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamsByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamsByTournamentRow
	for rows.Next() {
		var i GetTeamsByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TournamentID,
			&i.Started,
			&i.Finished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTeam = `-- name: StartTeam :exec
UPDATE teams SET started = 1 WHERE id = ?
`

func (q *Queries) StartTeam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, startTeam, id)
	return err
}
