// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_groups.sql

package db

import (
	"context"
	"database/sql"
)

const createTeamGroup = `-- name: CreateTeamGroup :one
INSERT INTO team_groups (name, tournament_id)
VALUES (?, ?)
RETURNING id, name, tournament_id, created_at
`

type CreateTeamGroupParams struct {
	Name         string
	TournamentID int64
}

func (q *Queries) CreateTeamGroup(ctx context.Context, arg CreateTeamGroupParams) (TeamGroup, error) {
	row := q.db.QueryRowContext(ctx, createTeamGroup, arg.Name, arg.TournamentID)
	var i TeamGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TournamentID,
		&i.CreatedAt,
	)
	return i, err
}

const addTeamToGroup = `-- name: AddTeamToGroup :exec
INSERT INTO team_group_members (team_id, group_id)
VALUES (?, ?)
`

type AddTeamToGroupParams struct {
	TeamID  int64
	GroupID int64
}

func (q *Queries) AddTeamToGroup(ctx context.Context, arg AddTeamToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addTeamToGroup, arg.TeamID, arg.GroupID)
	return err
}

const getTournamentGroups = `-- name: GetTournamentGroups :many
SELECT id, name, tournament_id, created_at
FROM team_groups
WHERE tournament_id = ?
`

func (q *Queries) GetTournamentGroups(ctx context.Context, tournamentID int64) ([]TeamGroup, error) {
	rows, err := q.db.QueryContext(ctx, getTournamentGroups, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamGroup
	for rows.Next() {
		var i TeamGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TournamentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournamentGroupMembers = `-- name: GetTournamentGroupMembers :many
SELECT tgm.team_id, tgm.group_id, tg.name as group_name
FROM team_group_members tgm
JOIN team_groups tg ON tgm.group_id = tg.id
WHERE tg.tournament_id = ?
`

type GetTournamentGroupMembersRow struct {
	TeamID    int64
	GroupID   int64
	GroupName string
}

func (q *Queries) GetTournamentGroupMembers(ctx context.Context, tournamentID int64) ([]GetTournamentGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTournamentGroupMembers, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTournamentGroupMembersRow
	for rows.Next() {
		var i GetTournamentGroupMembersRow
		if err := rows.Scan(&i.TeamID, &i.GroupID, &i.GroupName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTournamentReward = `-- name: CreateTournamentReward :one
INSERT INTO tournament_rewards (tournament_id, scope, metric, description)
VALUES (?, ?, ?, ?)
RETURNING id, tournament_id, scope, metric, description, created_at
`

type CreateTournamentRewardParams struct {
	TournamentID int64
	Scope        string
	Metric       string
	Description  sql.NullString
}

func (q *Queries) CreateTournamentReward(ctx context.Context, arg CreateTournamentRewardParams) (TournamentReward, error) {
	row := q.db.QueryRowContext(ctx, createTournamentReward,
		arg.TournamentID,
		arg.Scope,
		arg.Metric,
		arg.Description,
	)
	var i TournamentReward
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Scope,
		&i.Metric,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTournamentRewards = `-- name: GetTournamentRewards :many
SELECT id, tournament_id, scope, metric, description, created_at
FROM tournament_rewards
WHERE tournament_id = ?
`

func (q *Queries) GetTournamentRewards(ctx context.Context, tournamentID int64) ([]TournamentReward, error) {
	rows, err := q.db.QueryContext(ctx, getTournamentRewards, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TournamentReward
	for rows.Next() {
		var i TournamentReward
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.Scope,
			&i.Metric,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
