// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"
	"database/sql"
)

const addPlayerToTeam = `-- name: AddPlayerToTeam :exec
UPDATE players
SET team_id = ?
WHERE id = ?
`

type AddPlayerToTeamParams struct {
	TeamID int64
	ID     int64
}

func (q *Queries) AddPlayerToTeam(ctx context.Context, arg AddPlayerToTeamParams) error {
	_, err := q.db.ExecContext(ctx, addPlayerToTeam, arg.TeamID, arg.ID)
	return err
}

const checkTeamExists = `-- name: CheckTeamExists :one
SELECT id
FROM teams
WHERE id = ?
LIMIT 1
`

func (q *Queries) CheckTeamExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkTeamExists, id)
	err := row.Scan(&id)
	return id, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, tournament_id)
VALUES (?, ?)
RETURNING id, name, tournament_id, created_at
`

type CreateTeamParams struct {
	Name         string
	TournamentID sql.NullInt64
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.Name, arg.TournamentID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TournamentID,
		&i.CreatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, tournament_id, created_at FROM teams WHERE id = ?
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TournamentID,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamPlayers = `-- name: GetTeamPlayers :many
SELECT p.id, p.name, p.is_admin, p.handicap, p.active, p.course_tees_id, p.tournament_id, p.team_id, p.refreshtokenversion, p.created_at, ct.name as tee_name
FROM players p
JOIN course_tees ct ON p.course_tees_id = ct.id
  WHERE team_id = ?
ORDER BY p.name
`

type GetTeamPlayersRow struct {
	ID                  int64
	Name                string
	IsAdmin             sql.NullBool
	Handicap            sql.NullFloat64
	Active              bool
	CourseTeesID        int64
	TournamentID        int64
	TeamID              int64
	Refreshtokenversion int64
	CreatedAt           sql.NullTime
	TeeName             sql.NullString
}

func (q *Queries) GetTeamPlayers(ctx context.Context, teamID int64) ([]GetTeamPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamPlayers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamPlayersRow
	for rows.Next() {
		var i GetTeamPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsAdmin,
			&i.Handicap,
			&i.Active,
			&i.CourseTeesID,
			&i.TournamentID,
			&i.TeamID,
			&i.Refreshtokenversion,
			&i.CreatedAt,
			&i.TeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsByTournament = `-- name: GetTeamsByTournament :many
SELECT id, name, tournament_id, created_at
FROM teams
WHERE tournament_id = ?
ORDER BY teams.name
`

func (q *Queries) GetTeamsByTournament(ctx context.Context, tournamentID sql.NullInt64) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getTeamsByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TournamentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
