// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournaments.sql

package db

import (
	"context"
	"database/sql"
)

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (name, course_id, format_id, team_count, awarded_handicap, is_match_play, start_time, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, course_id, format_id, team_count, awarded_handicap, is_match_play, complete, start_time, created_at
`

type CreateTournamentParams struct {
	Name            string
	CourseID        sql.NullInt64
	FormatID        sql.NullInt64
	TeamCount       sql.NullInt64
	AwardedHandicap sql.NullFloat64
	IsMatchPlay     sql.NullBool
	StartTime       sql.NullTime
	CreatedAt       sql.NullTime
}

type CreateTournamentRow struct {
	ID              int64
	Name            string
	CourseID        sql.NullInt64
	FormatID        sql.NullInt64
	TeamCount       sql.NullInt64
	AwardedHandicap sql.NullFloat64
	IsMatchPlay     sql.NullBool
	Complete        sql.NullBool
	StartTime       sql.NullTime
	CreatedAt       sql.NullTime
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (CreateTournamentRow, error) {
	row := q.db.QueryRowContext(ctx, createTournament,
		arg.Name,
		arg.CourseID,
		arg.FormatID,
		arg.TeamCount,
		arg.AwardedHandicap,
		arg.IsMatchPlay,
		arg.StartTime,
		arg.CreatedAt,
	)
	var i CreateTournamentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CourseID,
		&i.FormatID,
		&i.TeamCount,
		&i.AwardedHandicap,
		&i.IsMatchPlay,
		&i.Complete,
		&i.StartTime,
		&i.CreatedAt,
	)
	return i, err
}

const getAllTournaments = `-- name: GetAllTournaments :many
SELECT id, name, course_id, format_id, team_count, awarded_handicap, is_match_play, complete, start_time, created_at 
FROM tournaments ORDER BY created_at DESC
`

type GetAllTournamentsRow struct {
	ID              int64
	Name            string
	CourseID        sql.NullInt64
	FormatID        sql.NullInt64
	TeamCount       sql.NullInt64
	AwardedHandicap sql.NullFloat64
	IsMatchPlay     sql.NullBool
	Complete        sql.NullBool
	StartTime       sql.NullTime
	CreatedAt       sql.NullTime
}

func (q *Queries) GetAllTournaments(ctx context.Context) ([]GetAllTournamentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTournamentsRow
	for rows.Next() {
		var i GetAllTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CourseID,
			&i.FormatID,
			&i.TeamCount,
			&i.AwardedHandicap,
			&i.IsMatchPlay,
			&i.Complete,
			&i.StartTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournament = `-- name: GetTournament :one
SELECT id, name, course_id, format_id, team_count, awarded_handicap, is_match_play, complete, start_time, created_at 
FROM tournaments WHERE id = ?
`

type GetTournamentRow struct {
	ID              int64
	Name            string
	CourseID        sql.NullInt64
	FormatID        sql.NullInt64
	TeamCount       sql.NullInt64
	AwardedHandicap sql.NullFloat64
	IsMatchPlay     sql.NullBool
	Complete        sql.NullBool
	StartTime       sql.NullTime
	CreatedAt       sql.NullTime
}

func (q *Queries) GetTournament(ctx context.Context, id int64) (GetTournamentRow, error) {
	row := q.db.QueryRowContext(ctx, getTournament, id)
	var i GetTournamentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CourseID,
		&i.FormatID,
		&i.TeamCount,
		&i.AwardedHandicap,
		&i.IsMatchPlay,
		&i.Complete,
		&i.StartTime,
		&i.CreatedAt,
	)
	return i, err
}
