// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournament_rounds.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTournamentRound = `-- name: CreateTournamentRound :one
INSERT INTO tournament_rounds (
    tournament_id,
    round_number,
    round_date,
    course_id,
    tee_set,
    name,
    status
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING
    id,
    tournament_id,
    round_number,
    round_date,
    course_id,
    tee_set,
    name,
    status,
    created_at
`

type CreateTournamentRoundParams struct {
	TournamentID int64
	RoundNumber  int64
	RoundDate    time.Time
	CourseID     int64
	TeeSet       string
	Name         string
	Status       sql.NullString
}

func (q *Queries) CreateTournamentRound(ctx context.Context, arg CreateTournamentRoundParams) (TournamentRound, error) {
	row := q.db.QueryRowContext(ctx, createTournamentRound,
		arg.TournamentID,
		arg.RoundNumber,
		arg.RoundDate,
		arg.CourseID,
		arg.TeeSet,
		arg.Name,
		arg.Status,
	)
	var i TournamentRound
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RoundNumber,
		&i.RoundDate,
		&i.CourseID,
		&i.TeeSet,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTournamentRound = `-- name: DeleteTournamentRound :exec
DELETE FROM tournament_rounds WHERE id = ?
`

func (q *Queries) DeleteTournamentRound(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTournamentRound, id)
	return err
}

const getActiveRounds = `-- name: GetActiveRounds :many
SELECT
    tr.id, tr.tournament_id, tr.round_number, tr.round_date, tr.course_id, tr.tee_set, tr.name, tr.status, tr.created_at,
    c.name AS course_name,
    t.name AS tournament_name
FROM tournament_rounds tr
JOIN courses c ON c.id = tr.course_id
JOIN tournaments t ON t.id = tr.tournament_id
WHERE tr.status = 'active'
ORDER BY tr.round_date, tr.round_number
`

type GetActiveRoundsRow struct {
	ID             int64
	TournamentID   int64
	RoundNumber    int64
	RoundDate      time.Time
	CourseID       int64
	TeeSet         string
	Name           string
	Status         sql.NullString
	CreatedAt      sql.NullTime
	CourseName     string
	TournamentName string
}

func (q *Queries) GetActiveRounds(ctx context.Context) ([]GetActiveRoundsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveRounds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveRoundsRow
	for rows.Next() {
		var i GetActiveRoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.RoundNumber,
			&i.RoundDate,
			&i.CourseID,
			&i.TeeSet,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.CourseName,
			&i.TournamentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournamentRound = `-- name: GetTournamentRound :one
SELECT
    tr.id, tr.tournament_id, tr.round_number, tr.round_date, tr.course_id, tr.tee_set, tr.name, tr.status, tr.created_at,
    c.name AS course_name
FROM tournament_rounds tr
JOIN courses c ON c.id = tr.course_id
WHERE tr.id = ?
`

type GetTournamentRoundRow struct {
	ID           int64
	TournamentID int64
	RoundNumber  int64
	RoundDate    time.Time
	CourseID     int64
	TeeSet       string
	Name         string
	Status       sql.NullString
	CreatedAt    sql.NullTime
	CourseName   string
}

func (q *Queries) GetTournamentRound(ctx context.Context, id int64) (GetTournamentRoundRow, error) {
	row := q.db.QueryRowContext(ctx, getTournamentRound, id)
	var i GetTournamentRoundRow
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RoundNumber,
		&i.RoundDate,
		&i.CourseID,
		&i.TeeSet,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.CourseName,
	)
	return i, err
}

const getTournamentRoundByNumber = `-- name: GetTournamentRoundByNumber :one
SELECT
    tr.id, tr.tournament_id, tr.round_number, tr.round_date, tr.course_id, tr.tee_set, tr.name, tr.status, tr.created_at,
    c.name AS course_name
FROM tournament_rounds tr
JOIN courses c ON c.id = tr.course_id
WHERE tr.tournament_id = ? AND tr.round_number = ?
`

type GetTournamentRoundByNumberParams struct {
	TournamentID int64
	RoundNumber  int64
}

type GetTournamentRoundByNumberRow struct {
	ID           int64
	TournamentID int64
	RoundNumber  int64
	RoundDate    time.Time
	CourseID     int64
	TeeSet       string
	Name         string
	Status       sql.NullString
	CreatedAt    sql.NullTime
	CourseName   string
}

func (q *Queries) GetTournamentRoundByNumber(ctx context.Context, arg GetTournamentRoundByNumberParams) (GetTournamentRoundByNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getTournamentRoundByNumber, arg.TournamentID, arg.RoundNumber)
	var i GetTournamentRoundByNumberRow
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RoundNumber,
		&i.RoundDate,
		&i.CourseID,
		&i.TeeSet,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.CourseName,
	)
	return i, err
}

const getTournamentRounds = `-- name: GetTournamentRounds :many
SELECT
    id,
    tournament_id,
    round_number,
    round_date,
    course_id,
    tee_set,
    name,
    status,
    created_at
FROM tournament_rounds
WHERE tournament_id = ?
ORDER BY round_number
`

func (q *Queries) GetTournamentRounds(ctx context.Context, tournamentID int64) ([]TournamentRound, error) {
	rows, err := q.db.QueryContext(ctx, getTournamentRounds, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TournamentRound
	for rows.Next() {
		var i TournamentRound
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.RoundNumber,
			&i.RoundDate,
			&i.CourseID,
			&i.TeeSet,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTournamentRound = `-- name: UpdateTournamentRound :exec
UPDATE tournament_rounds
SET
    round_date = ?,
    course_id = ?,
    tee_set = ?,
    name = ?,
    status = ?
WHERE id = ?
`

type UpdateTournamentRoundParams struct {
	RoundDate time.Time
	CourseID  int64
	TeeSet    string
	Name      string
	Status    sql.NullString
	ID        int64
}

func (q *Queries) UpdateTournamentRound(ctx context.Context, arg UpdateTournamentRoundParams) error {
	_, err := q.db.ExecContext(ctx, updateTournamentRound,
		arg.RoundDate,
		arg.CourseID,
		arg.TeeSet,
		arg.Name,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateTournamentRoundStatus = `-- name: UpdateTournamentRoundStatus :exec
UPDATE tournament_rounds
SET status = ?
WHERE id = ?
`

type UpdateTournamentRoundStatusParams struct {
	Status sql.NullString
	ID     int64
}

func (q *Queries) UpdateTournamentRoundStatus(ctx context.Context, arg UpdateTournamentRoundStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTournamentRoundStatus, arg.Status, arg.ID)
	return err
}
