// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournaments.sql

package db

import (
	"context"
	"database/sql"
)

const createTournament = `-- name: CreateTournament :one
INSERT INTO
    tournaments (
        name,
        format_id,
        team_count,
        awarded_handicap,
        is_match_play,
        start_date,
        end_date,
        total_rounds,
        start_time,
        created_at
    )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
    id,
    name,
    format_id,
    team_count,
    awarded_handicap,
    is_match_play,
    complete,
    start_date,
    end_date,
    total_rounds,
    start_time,
    created_at
`

type CreateTournamentParams struct {
	Name            string
	FormatID        sql.NullInt64
	TeamCount       sql.NullInt64
	AwardedHandicap sql.NullFloat64
	IsMatchPlay     sql.NullBool
	StartDate       sql.NullTime
	EndDate         sql.NullTime
	TotalRounds     sql.NullInt64
	StartTime       sql.NullTime
	CreatedAt       sql.NullTime
}

type CreateTournamentRow struct {
	ID              int64
	Name            string
	FormatID        sql.NullInt64
	TeamCount       sql.NullInt64
	AwardedHandicap sql.NullFloat64
	IsMatchPlay     sql.NullBool
	Complete        sql.NullBool
	StartDate       sql.NullTime
	EndDate         sql.NullTime
	TotalRounds     sql.NullInt64
	StartTime       sql.NullTime
	CreatedAt       sql.NullTime
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (CreateTournamentRow, error) {
	row := q.db.QueryRowContext(ctx, createTournament,
		arg.Name,
		arg.FormatID,
		arg.TeamCount,
		arg.AwardedHandicap,
		arg.IsMatchPlay,
		arg.StartDate,
		arg.EndDate,
		arg.TotalRounds,
		arg.StartTime,
		arg.CreatedAt,
	)
	var i CreateTournamentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FormatID,
		&i.TeamCount,
		&i.AwardedHandicap,
		&i.IsMatchPlay,
		&i.Complete,
		&i.StartDate,
		&i.EndDate,
		&i.TotalRounds,
		&i.StartTime,
		&i.CreatedAt,
	)
	return i, err
}

const getAllTournaments = `-- name: GetAllTournaments :many
SELECT
    id,
    name,
    course_id,
    format_id,
    team_count,
    awarded_handicap,
    is_match_play,
    complete,
    start_time,
    start_date,
    end_date,
    total_rounds,
    created_at
FROM tournaments
ORDER BY created_at DESC
`

type GetAllTournamentsRow struct {
	ID              int64
	Name            string
	CourseID        sql.NullInt64
	FormatID        sql.NullInt64
	TeamCount       sql.NullInt64
	AwardedHandicap sql.NullFloat64
	IsMatchPlay     sql.NullBool
	Complete        sql.NullBool
	StartTime       sql.NullTime
	StartDate       sql.NullTime
	EndDate         sql.NullTime
	TotalRounds     sql.NullInt64
	CreatedAt       sql.NullTime
}

func (q *Queries) GetAllTournaments(ctx context.Context) ([]GetAllTournamentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTournamentsRow
	for rows.Next() {
		var i GetAllTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CourseID,
			&i.FormatID,
			&i.TeamCount,
			&i.AwardedHandicap,
			&i.IsMatchPlay,
			&i.Complete,
			&i.StartTime,
			&i.StartDate,
			&i.EndDate,
			&i.TotalRounds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournament = `-- name: GetTournament :one
SELECT
    t.id, t.name, t.course_id, t.format_id, t.team_count, t.awarded_handicap, t.is_match_play, t.complete, t.created_at, t.start_time, t.start_date, t.end_date, t.total_rounds,
    tf.name AS format_name,
    tf.is_team_scoring AS is_team_scoring,
    tf.description AS tournament_format_description
FROM
    tournaments t
    JOIN tournament_formats tf ON tf.id = t.format_id
WHERE
    t.id = ?
`

type GetTournamentRow struct {
	ID                          int64
	Name                        string
	CourseID                    sql.NullInt64
	FormatID                    sql.NullInt64
	TeamCount                   sql.NullInt64
	AwardedHandicap             sql.NullFloat64
	IsMatchPlay                 sql.NullBool
	Complete                    sql.NullBool
	CreatedAt                   sql.NullTime
	StartTime                   sql.NullTime
	StartDate                   sql.NullTime
	EndDate                     sql.NullTime
	TotalRounds                 sql.NullInt64
	FormatName                  string
	IsTeamScoring               sql.NullBool
	TournamentFormatDescription sql.NullString
}

func (q *Queries) GetTournament(ctx context.Context, id int64) (GetTournamentRow, error) {
	row := q.db.QueryRowContext(ctx, getTournament, id)
	var i GetTournamentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CourseID,
		&i.FormatID,
		&i.TeamCount,
		&i.AwardedHandicap,
		&i.IsMatchPlay,
		&i.Complete,
		&i.CreatedAt,
		&i.StartTime,
		&i.StartDate,
		&i.EndDate,
		&i.TotalRounds,
		&i.FormatName,
		&i.IsTeamScoring,
		&i.TournamentFormatDescription,
	)
	return i, err
}
