// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournaments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTournament = `-- name: CreateTournament :one
INSERT INTO
    tournaments (
        name,
        team_count,
        start_date,
        end_date,
        created_at
    )
VALUES (?, ?, ?, ?, ?)
RETURNING
    id,
    name,
    team_count,
    complete,
    start_date,
    end_date,
    created_at
`

type CreateTournamentParams struct {
	Name      string
	TeamCount int64
	StartDate time.Time
	EndDate   time.Time
	CreatedAt sql.NullTime
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRowContext(ctx, createTournament,
		arg.Name,
		arg.TeamCount,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedAt,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamCount,
		&i.Complete,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getAllTournaments = `-- name: GetAllTournaments :many
SELECT
    id,
    name,
    team_count,
    complete,
    start_date,
    end_date,
    created_at
FROM tournaments
ORDER BY created_at DESC
`

func (q *Queries) GetAllTournaments(ctx context.Context) ([]Tournament, error) {
	rows, err := q.db.QueryContext(ctx, getAllTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamCount,
			&i.Complete,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournament = `-- name: GetTournament :one
SELECT
    t.id, t.name, t.team_count, t.complete, t.start_date, t.end_date, t.created_at,
    tf.name AS format_name,
    tf.description AS tournament_format_description
FROM
    tournaments t
    JOIN tournament_formats tf ON tf.id = t.format_id
WHERE
    t.id = ?
`

type GetTournamentRow struct {
	ID                          int64
	Name                        string
	TeamCount                   int64
	Complete                    bool
	StartDate                   time.Time
	EndDate                     time.Time
	CreatedAt                   sql.NullTime
	FormatName                  string
	TournamentFormatDescription sql.NullString
}

func (q *Queries) GetTournament(ctx context.Context, id int64) (GetTournamentRow, error) {
	row := q.db.QueryRowContext(ctx, getTournament, id)
	var i GetTournamentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamCount,
		&i.Complete,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.FormatName,
		&i.TournamentFormatDescription,
	)
	return i, err
}
