// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"encoding/json"
)

type ActiveTournamentPlayer struct {
	TournamentID int64
	PlayerID     int64
	CreatedAt    sql.NullTime
}

type Changelog struct {
	Namespace  int64
	Version    int64
	ClientID   string
	EntityType string
	EntityID   int64
	Op         string
	Data       json.RawMessage
}

type Course struct {
	ID        int64
	Name      string
	Data      json.RawMessage
	CreatedAt sql.NullTime
}

type CourseHole struct {
	ID         int64
	CourseID   int64
	TeeSet     string
	HoleNumber int64
	Par        int64
	Handicap   int64
	Yardage    int64
	CreatedAt  sql.NullTime
	HoleIndex  sql.NullInt64
}

type Entity struct {
	Namespace int64
	Type      string
	EntityID  int64
	Data      json.RawMessage
	UpdatedAt int64
	UpdatedBy string
}

type Invite struct {
	ID           int64
	Token        sql.NullString
	TournamentID int64
	TeamID       sql.NullInt64
	ExpiresAt    sql.NullTime
	CreatedAt    sql.NullTime
	Active       sql.NullBool
}

type Meta struct {
	Key   string
	Value int64
}

type Player struct {
	ID                  int64
	Name                string
	IsAdmin             sql.NullBool
	Handicap            sql.NullFloat64
	CreatedAt           sql.NullTime
	Refreshtokenversion int64
}

type Score struct {
	ID           int64
	TournamentID int64
	PlayerID     sql.NullInt64
	TeamID       sql.NullInt64
	CourseHoleID int64
	Strokes      int64
	CreatedAt    sql.NullTime
}

type Team struct {
	ID           int64
	Name         string
	TournamentID sql.NullInt64
	Started      sql.NullBool
	Finished     sql.NullBool
	CreatedAt    sql.NullTime
}

type TeamPlayer struct {
	TeamID   sql.NullInt64
	PlayerID sql.NullInt64
	Tee      sql.NullString
}

type Tournament struct {
	ID              int64
	Name            string
	CourseID        sql.NullInt64
	FormatID        sql.NullInt64
	TeamCount       sql.NullInt64
	AwardedHandicap sql.NullFloat64
	IsMatchPlay     sql.NullBool
	Complete        sql.NullBool
	CreatedAt       sql.NullTime
	StartTime       sql.NullTime
}

type TournamentFormat struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type TxContext struct {
	ClientID sql.NullString
}
